services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=nfclabs.com,www.nfclabs.com,89.40.6.100
    command: gunicorn NFCLabs.wsgi:application --bind 0.0.0.0:8000

  # Pašalintas nginx ir certbot - naudosime lokalų nginx

volumes:
  static_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/www/nfclabs_static'
  media_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/www/nfclabs_media'