# Generated by Django 5.2 on 2025-05-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('about', 'Apie mus'), ('products', 'Produktai'), ('solutions', 'Sprendimai'), ('home', 'Pagrindinis puslapis'), ('contact', 'Kontaktai')], max_length=50, unique=True, verbose_name='Puslapis')),
                ('title', models.CharField(max_length=200, verbose_name='Puslapio pavadinimas')),
                ('content', models.TextField(verbose_name='Turinys')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta aprašymas')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, verbose_name='Meta raktažodžiai')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinimo data')),
            ],
            options={
                'verbose_name': 'Puslapio turinys',
                'verbose_name_plural': 'Puslapių turiniai',
            },
        ),
    ]
