# Generated by Django 5.2 on 2025-05-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'verbose_name': 'Website Content', 'verbose_name_plural': 'Websites Content'},
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta keywords'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page_key',
            field=models.CharField(max_length=50, unique=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Data'),
        ),
    ]
