# Generated by Django 5.2 on 2025-05-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFCLabs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageContent',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='solutions/'),
        ),
    ]
