# Generated by Django 5.2 on 2025-05-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFCLabs', '0002_delete_pagecontent_alter_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact/')),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, help_text='Specific email for this contact type', max_length=254)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Pages',
                'ordering': ['order', 'name'],
            },
        ),
    ]
