# Generated by Django 5.2 on 2025-05-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFCLabs', '0003_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Additional information section'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='content',
            field=models.TextField(blank=True, help_text='Main content - can use HTML'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone',
            field=models.CharField(blank=True, help_text='Direct phone for this department', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='description',
            field=models.TextField(blank=True, help_text='Short description shown at the top'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='email',
            field=models.EmailField(blank=True, help_text='Direct email for this department', max_length=254),
        ),
    ]
