# Generated by Django 5.2 on 2025-05-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFCLabs', '0004_contactpage_additional_info_contactpage_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Contact Page', 'verbose_name_plural': 'Contact Pages'},
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='phone',
        ),
    ]
