# Generated by Django 5.2 on 2025-05-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFCLabs', '0005_alter_contactpage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Contact Page', 'verbose_name_plural': 'Contact Pages'},
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='description',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='content',
            field=models.TextField(default='', help_text='Puslapio turinys (galima naudoti HTML)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpage',
            name='order',
            field=models.IntegerField(default=0, help_text='Rikiavimo tvarka dropdown meniu'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='show_contact_form',
            field=models.BooleanField(default=False, help_text='Ar rodyti kontaktinę formą šiame puslapyje?'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_pages/'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
