# Generated by Django 5.2 on 2025-05-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFCLabs', '0006_alter_contactpage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='content',
            field=models.TextField(help_text='Puslapio turinys'),
        ),
    ]
