# Generated by Django 5.2 on 2025-05-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFCLabs', '0009_emailconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='default_from_email',
            field=models.CharField(default='Užklausa <ainius@nfc.lt>', help_text='Default sender email format', max_length=200, verbose_name='Default From Email'),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='email_host',
            field=models.CharField(default='gandras.serveriai.lt', help_text='SMTP server address', max_length=200, verbose_name='Email Host'),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='email_host_user',
            field=models.EmailField(default='ainius@nfc.lt', help_text='SMTP username/email', max_length=254, verbose_name='Email Host User'),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='email_port',
            field=models.IntegerField(default=465, help_text='SMTP server port', verbose_name='Email Port'),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='email_use_ssl',
            field=models.BooleanField(default=True, help_text='Enable SSL encryption', verbose_name='Use SSL'),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='email_use_tls',
            field=models.BooleanField(default=False, help_text='Enable TLS encryption', verbose_name='Use TLS'),
        ),
    ]
