# Generated by Django 5.2 on 2025-05-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFCLabs', '0010_emailconfig_default_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='video_url',
            field=models.URLField(blank=True, help_text='Video', max_length=500, null=True),
        ),
    ]
